### ISSUE TITLE
Docker configuration is not automatically applied with `eu.xenit.docker-compose` plugin

### ISSUE THREAD

**Issue by vierbergenlars** [xenit-eu/alfresco-docker-gradle-plugin#149]
When creating a simple project with only the `eu.xenit.docker-compose` plugin applied, basic configuration done by `eu.xenit.docker-config` is not applied.

This results in a hard to comprehend error when using `${DOCKER_IP}` interpolation for selecting the expose port:

```
Successfully started process 'command 'docker-compose''
The DOCKER_IMAGE variable is not set. Defaulting to a blank string.
The DOCKER_IP variable is not set. Defaulting to a blank string.
The Compose file './docker-compose.yml' is invalid because:
services.authentication-proxy.ports is invalid: Invalid port "::80", should be [[remote_ip:]remote_port[-remote_port]:]port[/protocol]
services.edge.ports is invalid: Invalid port "::8080", should be [[remote_ip:]remote_port[-remote_port]:]port[/protocol]
```

<details>
<summary>Project setup</summary>

```groovy
// build.gradle
plugins {
    id 'base'
    id 'eu.xenit.docker-compose'
}
```

```yml
# docker-compose.yml
version: "2"

services:
  edge:
    image: XXXX
    mem_limit: 200m
    ports:
        - ${DOCKER_IP}::8080

  authentication-proxy:
    build:
      context: authentication-proxy
    ports:
      - ${DOCKER_IP}::80
    command: "nginx"
    depends_on:
      - edge
```

</details>
